### PR TITLE
Initial Type Definitions

### PR DESCRIPTION
**Pull request by mrkmg**
Still have a few TODO's to iron out, mostly for the Mac calls as I do not have a machine running MacOS to test them with.

### CODE REVIEW

**Comment by mrkmg** [comment]
Please do not merge yet as there is an issue with some of the types. Fixing up now.

**Comment by mrkmg** [comment]
I believe this is all set now.

If you have any questions, please let me know.

**Comment by mrkmg** [comment]
If you do not want type def in this project, I can post to the https://github.com/DefinitelyTyped/DefinitelyTyped instead. Just wanted to give a change for them to be put in here first, as that is the recommended way of distributing types (as per the Typescript Team).

**Comment by zcbenz** [comment]
Thank you!

I'll include this in next release, which will take some time since the project is in the middle of a large refactoring.

**Comment by mrkmg** [comment]
After the refactor, I would like to make sure all the types are good still. I will keep an eye out!

**Comment by zaaack** [comment]
any updates here ?

**Pull request merged**
